const photocards = [
    {
        artist: "blackpink",
        title: "ROSE - -R- Photobook [Special Edition]",
        release: "2 Januari 2025",
        price: "290.000",
        image: "/photocard/rose-r.webp",
        href: "/detail",
    },
    {
        artist: "bts",
        title: "BTS V - ‘TYPE 1’",
        release: "28 Desember 2024",
        price: "500.000",
        image: "/photocard/bts_v_type1.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "ROSE - -R- Photobook [Special Edition]",
        release: "2 Januari 2025",
        price: "290.000",
        image: "/photocard/rose-r.webp",
        href: "/detail",
    },
    {
        artist: "Seventeen",
        title: "DICON VOLUME No. 26 (Unit-type) WONWOO MINGYU’",
        release: "27 februari 2025",
        price: "700.000",
        image: "/photocard/dicon_volume_26.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "ROSE - -R- Photobook [Special Edition]",
        release: "2 Januari 2025",
        price: "290.000",
        image: "/photocard/rose-r.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "ROSE - -R- Photobook [Special Edition]",
        release: "2 Januari 2025",
        price: "290.000",
        image: "/photocard/rose-r.webp",
        href: "/detail",
    },
    {
        artist: "bts",
        title: "BTS V - ‘TYPE 1’",
        release: "28 Desember 2024",
        price: "500.000",
        image: "/photocard/bts_v_type1.webp",
        href: "/detail",
    },
    {
        artist: "bts",
        title: "BTS V - ‘TYPE 1’",
        release: "28 Desember 2024",
        price: "500.000",
        image: "/photocard/bts_v_type1.webp",
        href: "/detail",
    },
    {
        artist: "bts",
        title: "BTS V - ‘TYPE 1’",
        release: "28 Desember 2024",
        price: "500.000",
        image: "/photocard/bts_v_type1.webp",
        href: "/detail",
    },
    {
        artist: "Seventeen",
        title: "DICON VOLUME No. 26 (Unit-type) WONWOO MINGYU’",
        release: "27 februari 2025",
        price: "700.000",
        image: "/photocard/dicon_volume_26.webp",
        href: "/detail",
    },
    {
        artist: "Seventeen",
        title: "DICON VOLUME No. 26 (Unit-type) WONWOO MINGYU’",
        release: "27 februari 2025",
        price: "700.000",
        image: "/photocard/dicon_volume_26.webp",
        href: "/detail",
    },
    {
        artist: "Seventeen",
        title: "DICON VOLUME No. 26 (Unit-type) WONWOO MINGYU’",
        release: "27 februari 2025",
        price: "700.000",
        image: "/photocard/dicon_volume_26.webp",
        href: "/detail",
    },
]

const albums = [
    {
        artist: "seventeen",
        title: "SEVENTEEN - SEVENTEEN BEST ALBUM [17 IS RIGHT HERE] DEAR Ver.",
        release: "6 Oktober 2024",
        price: "320.000",
        image: "/album/seventeen-best.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "(YG SELECT & KPOP MERCH Exclusive Benefit) JISOO - FIRST SINGLE ALBUM ME",
        release: "25 November 2024",
        price: "252.000",
        image: "/album/yg_select_bp.webp",
        href: "/detail",
    },
    {
        artist: "seventeen",
        title: "SEVENTEEN - SEVENTEEN BEST ALBUM [17 IS RIGHT HERE] DEAR Ver.",
        release: "6 Oktober 2024",
        price: "320.000",
        image: "/album/seventeen-best.webp",
        href: "/detail",
    },
    {
        artist: "LE SSERAFIM",
        title: "LE SSERAFIM - 4th Mini Album 'CRAZY' (BALACLAVA ver)",
        release: "1 Januari 2025",
        price: "505.000",
        image: "/album/lesserafim-album.webp",
        href: "/detail",
    },
    {
        artist: "seventeen",
        title: "SEVENTEEN - SEVENTEEN BEST ALBUM [17 IS RIGHT HERE] DEAR Ver.",
        release: "6 Oktober 2024",
        price: "320.000",
        image: "/album/seventeen-best.webp",
        href: "/detail",
    },
    {
        artist: "seventeen",
        title: "SEVENTEEN - SEVENTEEN BEST ALBUM [17 IS RIGHT HERE] DEAR Ver.",
        release: "6 Oktober 2024",
        price: "320.000",
        image: "/album/seventeen-best.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "(YG SELECT & KPOP MERCH Exclusive Benefit) JISOO - FIRST SINGLE ALBUM ME",
        release: "25 November 2024",
        price: "252.000",
        image: "/album/yg_select_bp.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "(YG SELECT & KPOP MERCH Exclusive Benefit) JISOO - FIRST SINGLE ALBUM ME",
        release: "25 November 2024",
        price: "252.000",
        image: "/album/yg_select_bp.webp",
        href: "/detail",
    },
    {
        artist: "blackpink",
        title: "(YG SELECT & KPOP MERCH Exclusive Benefit) JISOO - FIRST SINGLE ALBUM ME",
        release: "25 November 2024",
        price: "252.000",
        image: "/album/yg_select_bp.webp",
        href: "/detail",
    },
    {
        artist: "LE SSERAFIM",
        title: "LE SSERAFIM - 4th Mini Album 'CRAZY' (BALACLAVA ver)",
        release: "1 Januari 2025",
        price: "505.000",
        image: "/album/lesserafim-album.webp",
        href: "/detail",
    },
    {
        artist: "LE SSERAFIM",
        title: "LE SSERAFIM - 4th Mini Album 'CRAZY' (BALACLAVA ver)",
        release: "1 Januari 2025",
        price: "505.000",
        image: "/album/lesserafim-album.webp",
        href: "/detail",
    },
]

const fashions = [
    {
        artist: "nct 127",
        title: "NCT 127 - BLACK STARFISH DOLL KEYRING ‘NEO CITY : SEOUL – THE MOMENTUM’",
        release: "5 September 2024",
        price: "450.000",
        image: "/fashion/nct-blk-star.webp",
        href: "/detail",
    },
    {
        artist: "TWICE",
        title: "TWICE - LIGHT BAND KIT",
        price: "500.000",
        image: "/fashion/twice-lightband.webp",
        href: "/detail",
    },
    {
        artist: "nct 127",
        title: "NCT 127 - BLACK STARFISH DOLL KEYRING ‘NEO CITY : SEOUL – THE MOMENTUM’",
        release: "5 September 2024",
        price: "450.000",
        image: "/fashion/nct-blk-star.webp",
        href: "/detail",
    },
    {
        artist: "ENHYPEN",
        title: "ENHYPEN - 2022 GGU GGU PACKAGE",
        price: "650.000",
        image: "/fashion/enhypen-pack.webp",
        href: "/detail",
    },
    {
        artist: "ENHYPEN",
        title: "ENHYPEN - 2022 GGU GGU PACKAGE",
        price: "650.000",
        image: "/fashion/enhypen-pack.webp",
        href: "/detail",
    },
    {
        artist: "ENHYPEN",
        title: "ENHYPEN - 2022 GGU GGU PACKAGE",
        price: "650.000",
        image: "/fashion/enhypen-pack.webp",
        href: "/detail",
    },
    {
        artist: "DAY6",
        title: "DAY6 - OFFICIAL LIGHT BAND VER 3",
        price: "1.000.000",
        image: "/fashion/day6-lightband.webp",
        href: "/detail",
    },
    {
        artist: "DAY6",
        title: "DAY6 - OFFICIAL LIGHT BAND VER 3",
        price: "1.000.000",
        image: "/fashion/day6-lightband.webp",
        href: "/detail",
    },
    {
        artist: "nct 127",
        title: "NCT 127 - BLACK STARFISH DOLL KEYRING ‘NEO CITY : SEOUL – THE MOMENTUM’",
        release: "5 September 2024",
        price: "450.000",
        image: "/fashion/nct-blk-star.webp",
        href: "/detail",
    },
    {
        artist: "TWICE",
        title: "TWICE - LIGHT BAND KIT",
        price: "500.000",
        image: "/fashion/twice-lightband.webp",
        href: "/detail",
    },
    {
        artist: "TWICE",
        title: "TWICE - LIGHT BAND KIT",
        price: "500.000",
        image: "/fashion/twice-lightband.webp",
        href: "/detail",
    },
]

export { photocards, albums, fashions };